### ISSUE TITLE
Allow type-safe access to bug patterns

### ISSUE THREAD

**Issue by pemistahl** [tbroyer/gradle-errorprone-plugin#105]
Currently, this plugin only allows to pass bug pattern names as plain strings to the configuration. In my opinion, it would be much more elegant and helpful to collect all bug patterns in an enum so that one can benefit from code completion when configuring the plugin in a Gradle build. One would have to maintain the patterns in the enum, of course, and I would understand if you rejected my request because of that. Still, could you consider adding an enum like that?

So, instead of just doing that:

```kotlin
tasks.withType<JavaCompile> {
    options.errorprone {
        enable(
            "UnusedLabel", 
            "UnusedMethod", 
            "UnusedVariable"
        )
    }
}
```

I'd also like to be able to do that:

```kotlin
// This enum would have to be provided by the plugin
enum class BugPattern {
    // ...
    UNUSED_LABEL,
    UNUSED_METHOD,
    UNUSED_VARIABLE,
    // ...
}

tasks.withType<JavaCompile> {
    options.errorprone {
        enable(
            BugPattern.UNUSED_LABEL, 
            BugPattern.UNUSED_METHOD, 
            BugPattern.UNUSED_VARIABLE
        )
    }
}
```

If you think that this could be a worth addition to this plugin, I will gladly open a PR for this. Thanks in advance.

**Comment by tbroyer** [comment]
Having such a list creates a tighter link on Error Prone releases: currently I only have to track command-line options to update ErrorProneOptions and cut a release every once in a while; with such an enum, almost each Error Prone release would have to trigger a new release of the plugin because the enum would have changed (and if the plugin is not up-to-date with Error Prone, then this type-safe API loses its appeal)

I really don't think this is worth the burden, and it's definitely not a burden I'm willing to commit to.

…but feel free to create your own plugin building upon this one and only providing Kotlin extension functions and that enum class (and if it's linked to a specific version of Error Prone, it could possibly automatically configure the dependency as well).

```kotlin
enum class BugPattern(val checkName: String) {
    // …
    UNUSED_LABEL("UnusedLabel"),
    // …
}

fun ErrorProneOptions.enable(vararg checkNames: BugPattern) = this.enable(*checkNames.map(BugPattern::checkName))
```
