### ISSUE TITLE
Error: plug-in not found: ErrorProne when using Kapt

### ISSUE THREAD

**Issue by alapshin** [tbroyer/gradle-errorprone-plugin#11]
I'm trying to migrate Android project from plugin version 0.0.16 to 0.6 however compilation fails with
```
> Task :app:compileDebugJavaWithJavac FAILED
error: plug-in not found: ErrorProne
```

When running build with `./gradlew --info compileDebugSources`  there is more info

```
Starting process 'Gradle Worker Daemon 13'. Working directory: /home/alapshin/.gradle/workers Command: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-5.fc29.x86_64/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Xbootclasspath/p:/home/alapshin/.gradle/caches/modules-2/files-2.1/com.google.errorprone/javac/9+181-r4173-1/bdf4c0aa7d540ee1f7bf14d47447aea4bbf450c5/javac-9+181-r4173-1.jar -Dfile.encoding=UTF-8 -Duser.country=IE -Duser.language=en -Duser.variant -cp /home/alapshin/.gradle/caches/4.9/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 13'
Successfully started process 'Gradle Worker Daemon 13'
Started Gradle worker daemon (0.262 secs) with fork options DaemonForkOptions{executable=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-5.fc29.x86_64/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[-Xbootclasspath/p:/home/alapshin/.gradle/caches/modules-2/files-2.1/com.google.errorprone/javac/9+181-r4173-1/bdf4c0aa7d540ee1f7bf14d47447aea4bbf450c5/javac-9+181-r4173-1.jar], classpath=[], keepAliveMode=SESSION}.
Compiling with JDK Java compiler API.
error: plug-in not found: ErrorProne
```

Versions of components:
java: 1.8.0_181
gradle: 4.9
android gradle plugin: 3.2.1
errorprone: 2.3.2
errorproneJavac: 9+181-r4173-1
gradle-errorprone-plugin: 0.6

**Comment by tbroyer** [comment]
That would mean that Error Prone is not passed in the `-processorpath` to the Java compiler, either because no `-processorpath` is passed at all, or it's missing Error Prone.

You could run with `--debug` and look for `Java compiler arguments:` line, and look at the results of `./gradlew dependencies --configuration debugAnnotationProcessor`.

Do you have any specific configuration around dependencies that could have excluded Error Prone? Or any specific configuration of the `options.annotationProcessorPath` on the task? or maybe disable annotation processing with `-proc:none`? (Gradle would then omit the `-processorpath`, this will be fixed in Gradle 5) Maybe some bad interaction with another plugin? (Kotlin Kapt plugin will disable annotation processing for instance)

**Comment by alapshin** [comment]
> You could run with --debug and look for `Java compiler arguments:` line

I tried `./gradlew --debug compileDebugSources > log.txt` but there is no such line in the log. No `-processorpath` either.

> ./gradlew dependencies --configuration debugAnnotationProcessor

This didn't work however `./gradlew app:dependencies --configuration debugAnnotationProcessor` did. Output:

```
debugAnnotationProcessor - Classpath for the annotation processor for 'debug'. (n)
No dependencies
```

> Do you have any specific configuration around dependencies that could have excluded Error Prone?

I don't think so.

> Or any specific configuration of the options.annotationProcessorPath on the task?
> Maybe some bad interaction with another plugin? (Kotlin Kapt plugin will disable annotation processing for instance)

There is no specific configuration of options.annotationProcessorPath as far as I can tell. However project uses Kotlin Kapt plugin.

**Comment by alapshin** [comment]
Ok, thank you very much for the explanation. I will continue to use 0.0.16 for the time being.
