### ISSUE TITLE
How does one actually use java 10/11 with this?

### ISSUE THREAD

**Issue by xenoterracide** [tbroyer/gradle-errorprone-plugin#13]
used to be at least that it downloaded its own version of the compiler... but since it's a plugin, is that still required? is it possible to use the same version of the jdk that is running gradle? looking for docs on how to achieve.

**Comment by tbroyer** [comment]
With JDK 8, Error Prone will use the Error Prone Javac, configured as dependency in `errorproneJavac` configuration (unless the task is configured to use another JDK than the one that is running Gradle). Otherwise, it'll use the compiler from the JDK.

Contrary to the v0.0.x plugin, this plugin _only_ adds the `-Xplugin:ErrorProne …` argument (a bit more when using JDK 8, see the README); the Gradle semantics don't change: you can configure your tasks to fork, use specific JDKs, etc. everything will work the same as standard Gradle without the plugin.

So, to answer your question about how to use Java 10/11: either you run Gradle with those versions, and tasks will default to using that JDK; or you can configure the tasks to fork and use a specific JDK.

**Comment by tbroyer** [comment]
v0.0.x works in a totally different way: it will always compile with the Error Prone Javac (hijacking the Gradle compiler using internal APIs, so you can't fork compilation, and are probably losing other Gradle features, such as incremental annotation processing, possibly even incremental compilation), and cannot be used with JDK 10+

Those are all reasons why v0.0.x (https://github.com/tbroyer/gradle-errorprone-plugin-v0.0.x) is discontinued.

Wrt your Kotlin issue, this is only when testing with Gradle TestKit right? There must be some workarounds that would allow you to get your tests to pass (off the top of my head, switching your build to the Kotlin DSL and adding `embeddedKotlin()` as a `testRuntime` dependency)

**Comment by tbroyer** [comment]
You'll notice that I've linked `v0.0.x` in the README to the repo for the old plugin, whose README only lists compatibility with JDK 9.

I had wondered if I should add a more prominent message that this is the "newer" plugin, originally developed under the name `net.ltgt.errorprone-javacplugin`. Would it have helped?

Suggestions to improve the README are welcome (we can continue to chat here)

**Comment by xenoterracide** [comment]
maybe? but probably not, the other issue, is kind of a thorne, being a continuous problem (I clarified that I was using the older above 'cause I wasn't sure if that was impacting it). 

I guess what I might suggest is saying more explictly that, will use the JDK gradle uses unless.... blah. In this case it's also partially a problem just because of the confusion of how the JDK 9 variant originally worked. So it's a "behavior change" that if you were familliar feels like it requires clarification.

I've no right answers here, my solution to answering peoples questions about my code if it's not a bug is to write documentation, or try to otherwise make it clearer. But then who reads documentation ;)
