### ISSUE TITLE
Warning for errorproneJavac even on Java 10, when using com.github.ben-manes.versions plugin

### ISSUE THREAD

**Issue by boris-petrov** [tbroyer/gradle-errorprone-plugin#5]
I'm on Java 10 and when I run `gradle dependecyUpdates` (from [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin)) I get:

```
No dependency was configured in configuration errorproneJavac, compilation with Error Prone will likely fail as a result.
Add a dependency to com.google.errorprone:javac with the appropriate version corresponding to the version of Error Prone you're using:

    dependencies {
        errorproneJavac("com.google.errorprone:javac:$errorproneJavacVersion")
    }
```

I looked at your code and I'm not sure why this could happen. I printed:

```gradle
dependencyUpdates.doLast {
	println System.getProperty("java.version")
	println org.gradle.api.JavaVersion.current()
}
```

And this gives:

```
10.0.2
1.10
```

Compilation and other tasks work fine. Any ideas?

**Comment by tbroyer** [comment]
The warning is emitted when the `errorproneJavac` configuration is resolved. This normally only ever happens when running with JDK 8, but `com.github.ben-manes.versions` will resolve all configurations in the project, so it will trigger the code that emits the warning.

You can safely ignore the warning when using `com.github.ben-manes.versions` tasks. Alternatively, you could still configure a dependency in that configuration, it will only ever be resolved by dependency update tasks looking for new versions. :man_shrugging:

**Comment by tbroyer** [comment]
So, I've been thinking a bit more about this, and changed what triggers the warning. It should now (in the upcoming 0.6 release) be emitted when the first compilation task actually needs to use it, and simply resolving the configuration won't produce the warning anymore.

**Comment by boris-petrov** [comment]
Thanks a lot, that sounds perfect!
