### ISSUE TITLE
ignore `$buildDir/generated/source`

### ISSUE THREAD

**Issue by xenoterracide** [tbroyer/gradle-errorprone-plugin#54]
so... due to craziness maybe have an inclusive option to ignore generated code? I have this

```kts
    disableWarningsInGeneratedCode.set(true)
    excludedPaths.set("$buildDir/generated/sources/.*")
```

I'm still not certain that how I'm specifying the path for excluded paths is the best way to do it... but it might be nice to have a

```kts
disableGeneratedCodeCheck()
```

or some such, that does this for you. Also it might be good to change `excludedPaths` to a collection, and then you can join them yourself, that way the above would "add" it to the collection, and not simply override it. at minimum might be good to document how to exclude this directory.

**Comment by tbroyer** [comment]
If you configure the property with `$buildDir`, then your build is not _relocatable_, but that should otherwise work. I would prefer `".*/build/generated/sources/.*"` though.

A more generic approach would be to use something like the following so you're not hard-coding any conventional path (that will break if the directory is reconfigured to something outside the project directory, but that's very unlikely to ever happen):
```kotlin
excludedPaths.set(generatedSourceOutputDirectory.map { """.*/\Q${relativePath(it)}\E/*""" })
```

Maybe that last bit could be added to the README; not sure it's compatible with configuration cache though (and with Windows BTW), so maybe an `excludeGeneratedSourceOutputDirectory()` would help here…

**Comment by xenoterracide** [comment]
`$buildDir` is set by gradle so why would it not be relocatable? `excludeGeneratedSourceOutputDirectory()` would it be possible to use a sourceset? I don't really know how to do that in that case...

**Comment by tbroyer** [comment]
`$buildDir` is an absolute path, so you're setting `excludedPaths` to something like `/home/xenoterracide/Projects/myproject/build/generated/sources/*`. This value will be used in cache keys, so moving your project around (or using a shared build cache between developers/machines) will generate cache misses.

Using `Project#relativePath()` on `CompileOptions#generatedSourceOutputDirectory` makes it possible to generate a value of `.*/\Qbuild/generated/sources/annotationProcessor/java/main\E/.*` (for the `compileJava` task using default/conventional values) which then is relocatable (as it's relative to your project's directory).

The `excludeGeneratedSourceOutputDirectory()` I was talking about would _just_ be a builtin (to the plugin) equivalent to the code using `relativePath` and `generatedSourceOutputDirectory`, with possible additional tweaks for Windows compatibility (in retrospect, I think that code should be compatible with the configuration cache). I'm not going to rush adding such a helper though, as I think it's rather an edge-case (I personally prefer `disableWarningsInGeneratedCode`, along with `-Werror` so warnings in non-generated code are turned into errors), and `.*/build/generated/sources/.*` or `.*/build/generated/sources/annotationProcessor/.*` should be enough for most people otherwise.

If the `relativePath`+`generatedSourceOutputDirectory` works, I could however possibly add it to the README, along with the alternatives and their pros and cons.

**Comment by xenoterracide** [comment]
> $buildDir is an absolute path, so you're setting excludedPaths to something like

except if I move the project to another directory wouldn't that variable update?

> `disableWarningsInGeneratedCode`

this did not work for me with the immutables library, at all. hence this path. I filed an issue with error prone.

**Comment by tbroyer** [comment]
> > $buildDir is an absolute path, so you're setting excludedPaths to something like
> 
> except if I move the project to another directory wouldn't that variable update?

Yes, and that's what lead to cache misses, because the property value depends on where the project lives.
Might not be a problem in your case though.
Only leads to task reruns when their outputs could have been restored from cache.

> > `disableWarningsInGeneratedCode`
> 
> this did not work for me with the immutables library, at all. hence this path. I filed an issue with error prone.

Didn't remember the details but might be due to checks that you promoted to error. Having them as warnings would get them ignored, and `-Werror` would promote the ones in your own code to errors. Doesn't fit all setups, depending one whether you'd like to keep some checks as mere warnings.

**Comment by xenoterracide** [comment]
Not a fan of warnings, I should be releasing this code as open source in the following week or so, do you want to look at why this was the case? otherwise we can close this.

**Comment by tbroyer** [comment]
> Not a fan of warnings

Me neither, hence `-Werror`; in which case you can configure ErrorProne checks as warnings (promoted to errors by JavaC in the end) such that they'll be ignored for generated code.

**Comment by xenoterracide** [comment]
> -Werror would promote the ones in your own code to errors. 

ok, then maybe I don't understand, how would this not catch the generated code, vs the fact that I just have an incredibly long list of stuff I made errors.

**Comment by tbroyer** [comment]
When a check emit a failure, if it's configured as a warning, then ErrorProne looks if it's in generated code. If so, it'll omit the warning (`disableWarningsInGeneratedCode`), otherwise it emits it as usual.
Later on, at the end of the compilation, if a warning has been emitted (which can only be the case for non-generated code then) then JavaC reports a compilation failure (`-Werror`)

**Comment by xenoterracide** [comment]
hmm... this command line is confusing... are experimental warnings warnings by default?

**Comment by xenoterracide** [comment]
would you consider having `disableWarningsInGeneratedCode` also enabling `-WError`? or maybe have a property just for it and document that you need to do both.

**Comment by tbroyer** [comment]
The goal of this plugin is _only_ to make it easier to configure ErrorProne, I don't want to add features or even _helpers_ **unless** ones would be really needed due to usage in Gradle (I haven't seen any need for that), as anything that "automatically does X when you do Y" (particularly if Y has the same name as the Y in ErrorProne itself) could cause issues for some people so needs to be disableable, etc.
Put differently, the plugin aims at answering "how do I pass X to ErrorProne?", and not raising any question like "if I do Y with the plugin, what ErrorProne arguments does it really map to?"

So no, `disableWarningsInGeneratedCode` will never enable `-Werror`, it'll always only map to ErrorProne's `-XepDisableWarningsInGeneratedCode`.

I'm not opposed to an `excludeGeneratedSourceOutputDirectory()` but I don't think it's a good idea. As I said, for most people, `excludePaths.set(".*/build/generated/sources/annotationProcessor/.*")` will be enough; being smarter (such as basing the value on the `$buildDir` and/or `generatedSourceOutputDirectory`) can only be actually useful inside other plugins that want to be safe in case the project reconfigures those directories.
And as I said above, as soon as someone wants to exclude more (or less) code, they'll have to revert to using `excludePaths` directly anyway.

Regarding documentation, that means that the ErrorProne documentation by itself should be enough, and the plugin's documentation answers the "how do I do it with Gradle?" question. It could however add some documentation for things that are specific to Gradle, so documenting the `.*/build/generated/sources/annotationProcessor/.*` value could have its place there.

**Comment by xenoterracide** [comment]
ok, I tried this, did I put the comment somewhere else?

```java
    var foo = 2;
    var bar = 3;
    bar = 4;
    var overwrite = skel.getOverwrite();
    overwrite.booleanValue();
```

```kts
tasks.withType<JavaCompile>().configureEach {
  options.compilerArgs.addAll(listOf("-parameters", "-Xlint:deprecation", "-Xlint:unchecked"))

  options.errorprone {
    nullaway {
      severity.set(CheckSeverity.WARN)
      acknowledgeRestrictiveAnnotations.set(true)
      handleTestAssertionLibraries.set(true)
      checkOptionalEmptiness.set(true)
    }
    errorproneArgs.set(listOf("-Werror"))
    disableWarningsInGeneratedCode.set(true)
    excludedPaths.set("$buildDir/generated/sources/.*")
    error(
      "AmbiguousMethodReference",
       ...
    )
    warn(
      "Var" // I'd love for this to be inn the default error list, but it experimental :'(
    )
```

they're all warnings not errors
```
/Users/calebcushing/IdeaProjects/ppm/scaf/src/main/java/com/xenoterracide/scaf/PebbleTemplateProcessor.java:90: warning: [UnusedVariable] The local variable 'bar' is never read.
    var bar = 3;
        ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
/Users/calebcushing/IdeaProjects/ppm/scaf/src/main/java/com/xenoterracide/scaf/PebbleTemplateProcessor.java:89: warning: [UnusedVariable] The local variable 'foo' is never read.
    var foo = 2;
        ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean to remove this line?
/Users/calebcushing/IdeaProjects/ppm/scaf/src/main/java/com/xenoterracide/scaf/PebbleTemplateProcessor.java:90: warning: [Var] Non-constant variable missing @Var annotation
    var bar = 3;
        ^
    (see https://errorprone.info/bugpattern/Var)
  Did you mean '@Var var bar = 3;'?
/Users/calebcushing/IdeaProjects/ppm/scaf/src/main/java/com/xenoterracide/scaf/PebbleTemplateProcessor.java:93: warning: [NullAway] dereferenced expression overwrite is @Nullable
    overwrite.booleanValue();
             ^
    (see http://t.uber.com/nullaway )
```

**Comment by tbroyer** [comment]
`-Werror` is a JavaC argument, so `options.compilerArgs`, not `options.errorprone.errorproneArgs`.
(note that they'll stay warnings, but the compilation will fail with an error saying that there have been warnings)

**Comment by xenoterracide** [comment]
still get them on my generated class

```kts
tasks.withType<JavaCompile>().configureEach {
  options.compilerArgs.addAll(listOf("-parameters", "-Werror", "-Xlint:deprecation", "-Xlint:unchecked"))

  options.errorprone {
    nullaway {
      severity.set(CheckSeverity.WARN)
      acknowledgeRestrictiveAnnotations.set(true)
      handleTestAssertionLibraries.set(true)
      checkOptionalEmptiness.set(true)
    }
    disableWarningsInGeneratedCode.set(true)
    // excludedPaths.set(".*/build/generated/sources/annotationProcessor/.*")
```

**Comment by xenoterracide** [comment]
yeah, coming back to this, still a problem

```kts
tasks.withType<JavaCompile>().configureEach {
  options.compilerArgs.addAll(listOf(
    "-parameters",
    "-Werror",
    "-Xlint:deprecation",
    "-Xlint:unchecked"
  ) )
  options.errorprone {
    nullaway {
      severity.set(CheckSeverity.ERROR)
      acknowledgeRestrictiveAnnotations.set(true)
      handleTestAssertionLibraries.set(true)
    }
    disableWarningsInGeneratedCode.set(true)

    error(...
 ```

```
/home/xeno/IdeaProjects/adhoc/proto/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/uplogix/TxnLogDtoBuilder.java:45: error: [NullAway] initializer method does not guarantee @NonNull fields type (line 29), timestamp (line 30), amount (line 32) are initialized along all control-flow paths (remember to check for exceptions or early returns).
  public TxnLogDtoBuilder() {
         ^
    (see http://t.uber.com/nullaway )
2 errors
```

I'm kinda just glad this ticket is still open so I can see my fix.

and this doesn't compile in `build.gradle.kts`

```kts
  val generatedSourceOutputDirectory = options.generatedSourceOutputDirectory;
  options.compilerArgs.addAll(listOf(
    "-parameters",
    "-Werror",
    "-Xlint:deprecation",
    "-Xlint:unchecked"
  ) )
  options.errorprone {
    nullaway {
      severity.set(CheckSeverity.ERROR)
      acknowledgeRestrictiveAnnotations.set(true)
      handleTestAssertionLibraries.set(true)
    }
    disableWarningsInGeneratedCode.set(true)
    excludedPaths.set(generatedSourceOutputDirectory.map { """.*/\Q${relativePath(it)}\E/*""" })
```
```
* What went wrong:
Circular dependency between the following tasks:
:compileJava
\--- :compileJava (*)
```

**Comment by tbroyer** [comment]
I think this is a bug in Gradle, I've opened an issue: https://github.com/gradle/gradle/issues/16604

Note that with Gradle < 7, it's possible to use an intermediary provider to break the circular dependency. In Gradle 6 you'll have a deprecation warning though (see linked issue, where this is described, with code snippet)

I'm going to close this as I don't think there's anything I can do here.

**Comment by tbroyer** [comment]
Fwiw, I was told yesterday about [FileSystemLocationProperty.getLocationOnly()](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileSystemLocationProperty.html#getLocationOnly()) that would solve this issue:
```kotlin
excludedPaths.set(generatedSourceOutputDirectory.locationOnly.map { """.*/\Q${relativePath(it)}\E/*""" })
```

**Comment by xenoterracide** [comment]
Honestly, I still have this, and still feel like this probably needs a better API. 

If that's a solution that generally works, why not make it the default value if `disableWarningsInGeneratedCode` is set? or make an entirely new api for the gradle problem that does better.

```
    disableWarningsInGeneratedCode.set(true)
    excludedPaths.set(".*/build/generated/sources/annotationProcessor/.*")
```

I got curious if I still even needed that line. Yep. TBH, I'm not even certain what `disableWarningsInGenerateCode` does, it does not appear to have any positive impact on my code at all. Certainly isn't looking at the `@Generated` annotation, or if it is, not correctly.

> Fwiw, I was told yesterday about [FileSystemLocationProperty.getLocationOnly()](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileSystemLocationProperty.html#getLocationOnly()) that would solve this issue:

I'd have to translate that code into kotlin to test it, so I'll take your word on it. AFAIK, there's no benefit to doing it that way if you're not relocating your build? where 80% of my performance issue in CI are caused by gradle...

**Comment by tbroyer** [comment]
It looks at `@Generated` but only disabled warnings, not errors, so it's different from excluding the `generatedSourcesOutputDirectory`: you can have generated code in your sources (generated by another task), you can have errors in annotation-processor-generated code, and it might not be annotated with `@Generated`.

**Comment by xenoterracide** [comment]
Oh, right and because I basically convert everything I want to be an error because I think warnings are silly general. If I don't think it should apply then I suppress the warning otherwise it should be an error. Experience tells me that people ignore warnings. Somewhat rightly so because there are other people who refuse to stop emitting warnings from their code... The only warnings in my current code base for my project simply come from other people's code...

Anyways, I don't think you're going to do anything but here's hoping that you find some way of improving this situation/API for consumers of your plug-in.
