### ISSUE TITLE
migration from 0.0.x with plain old java

### ISSUE THREAD

**Issue by xenoterracide** [tbroyer/gradle-errorprone-plugin#6]
so your readme says this won't work anymore... but... how do I write the new thing in Java? I extend your plugin with my own in Java, and there's no errorProne() method on the class (unsurprisingly)

         options.getCompilerArgs().addAll( Arrays.asList(
                    "-XepExcludedPaths:.*/build/generated/.*",
                    "-Xep:MissingOverride:ERROR",
                    "-Xep:Var:ERROR"
            ) );

**Comment by tbroyer** [comment]
Should be something like

```java
((ExtensionAware) options).getExtensions().getByType(ErrorProneOptions.class)
```

**Comment by xenoterracide** [comment]
you're welcome to have a gander at my code https://bitbucket.org/xenoterracide/gradle-plugin-bundle/src/master/src/main/java/com/xenoterracide/gradle/plugin/configurations/ErrorProne.java currently I've locked the version to 0.0.x, but I don't see how to achieve what you suggest if I move it to 0.6

**Comment by xenoterracide** [comment]
urgh, that was intellij needing a manual refresh, however, now my test blows up with class not found. https://bitbucket.org/xenoterracide/gradle-plugin-bundle/addon/pipelines/home#!/results/117

**Comment by tbroyer** [comment]
The extension is not present on the project, but on the `CompileOptions` of the `JavaCompile` tasks.

**Comment by xenoterracide** [comment]
P.S. I could open an issue, but it's not that big of a deal to me. Might be easier to write the following instead of 2 lining it

```
ep.check( CheckSeverity.ERROR, "MissingOverride", "Var"  );
```

**Comment by xenoterracide** [comment]
it would appear that this kotlin missing class issue only happens on 0.6, and only when being run from my java plugin... if I use 0.6 in the kotlin dsl, and configure with the kotlin dsl, it works fine. So why doesn't it work with the Java API?

**Comment by tbroyer** [comment]
You may have to add an explicit dependency on Gradle's kotlin-dsl, as it's not transitive (being provided by Gradle at runtime)

**Comment by xenoterracide** [comment]
opening upstream ticket, because this is kind of crappy... obviously my code is executed through gradle including using the DSL, I'm not sure how to resolve as you're relying on a transitive gradle API, that for some reason isn't exported by either your plugin, or gradle itself... for right now I've simply decided to rely on 0.0.x

**Comment by xenoterracide** [comment]
> Wrt your Kotlin issue, this is only when testing with Gradle TestKit right? There must be some workarounds that would allow you to get your tests to pass (off the top of my head, switching your build to the Kotlin DSL and adding embeddedKotlin() as a testRuntime dependency)

moving this conversation back over here, so as to be focused... I probably could add that, my build already uses the dsl though... but that makes me wonder, maybe you should be exporting `embeddedKotlin` as `api`? just feels like there's a dependency that is required that nothing is saying I have it... it's not on the classpath... now yeah I could add it, but it's not really my dep. That said I didn't know it was `embeddedKotlin` before.

this code looks very suspicous, like if that library was on the classpath this exception wouldn't happen... 

https://github.com/tbroyer/gradle-errorprone-plugin/blob/d36cf009776592cd6bed22d49a3265583a3d8d2f/build.gradle.kts#L42-L47

**Comment by tbroyer** [comment]
> moving this conversation back over here, so as to be focused...

Thanks

> I probably could add that, my build already uses the dsl though...

But it does not add `testRuntime(embeddedKotlin("stdlib"))`, or alternatively apply the `org.gradle.kotlin.embedded-kotlin` plugin, which will automatically add it to the `compileOnly` and `testRuntime` (among other things, see https://github.com/gradle/kotlin-dsl/blob/v1.0-RC6/subprojects/plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPlugin.kt)

> but that makes me wonder, maybe you should be exporting `embeddedKotlin` as `api`?

No, because the version depends on the version of Gradle you're using, and you'd really want to use the embedded version at runtime.

> just feels like there's a dependency that is required that nothing is saying I have it... it's not on the classpath... now yeah I could add it, but it's not really my dep. That said I didn't know it was `embeddedKotlin` before.

The problem really is on Gradle's side, that should possibly automatically add the embedded kotlin dependency the same way it adds `localGroovy()`.

If someone wanted to depend on any Gradle plugin in its build, he would have to explicitly add `gradleApi()` and `localGroovy()` (or any Groovy) dependencies, because those are supposed to be provided at runtime (similar to `<scope>provided</scope>` in a Maven POM). This is the same here: you're depending on my plugin, which needs `kotlin-stdlib`, which in turn is generally provided by Gradle at runtime; so you need to add the dependencies explicitly for your non-TestKit tests to run.

> this code looks very suspicous, like if that library was on the classpath this exception wouldn't happen...

No. The Android plugin declares a dependency on `kotlin-stdlib-jre8`, which is deprecated in recent versions of Kotlin (like the one used by the version of Gradle that I use), replaced with `kotlin-stdlib-jdk8`. And `kotlin-stdlib-jdk8` is already present in the classpath, added by the `kotlin-dsl` plugin (which applies the `embedded-kotlin` plugin linked above).

---

I suggest closing this issue, in favor of https://github.com/gradle/gradle/issues/6859.

**Comment by xenoterracide** [comment]
thanks for the more detailed explanation, and commenting on the upstream issue.

> If someone wanted to depend on any Gradle plugin in its build, he would have to explicitly add gradleApi() and localGroovy() (or any Groovy) dependencies, because those are supposed to be provided at runtime (similar to <scope>provided</scope> in a Maven POM).

right, I said api, didn't mean that so much as, well... I guess I'm wondering if `runtime( embeddedKotlin() )` on your end would result in my end having that kicked up. I wonder if it's the appropriate solution. However Now that I'm starting to understand how I can fix this I might be ok adapting a solution. Though as I'm saying, I'm a little concerned still that I'd just be working around what you should be setting as a dependency. But without any real response from the gradle team, I can't say with 100% certainty what they are expecting.

I'll close this for now, I'll reopen/comment if necessary

**Comment by tbroyer** [comment]
It looks like you're not configuring the Error Prone dependency. v0.0.x used to configure it automatically as `latest.release`, but v0.x no longer does, and it must be added explicitly.

But adding `runtimeOnly(embeddedKotlin("stdlib"))` (which I believe should rather be `testImplementation`) at least fixed the earlier `NoClassDefFoundError`.

**Comment by tbroyer** [comment]
Ah, hadn't looked at the `XenoPluginTest` results. Looks like this is missing the `gradleKotlinDsl()` dependency now.

You should be able to replace `embeddedKotlin("stdlib")` with `gradleKotlinDsl()`.

**Comment by xenoterracide** [comment]
weird, [gradle looks really unhappy with jdk11](https://bitbucket.org/xenoterracide/gradle-plugin-bundle/addon/pipelines/home#!/results/162)

but [jdk 10 looks like it works](https://bitbucket.org/xenoterracide/gradle-plugin-bundle/addon/pipelines/home#!/results/163)

will push a new version and see how it works on a downstream project

**Comment by xenoterracide** [comment]
I can be satisfied, I don't think the 11 issue has anything to do with this plugin

**Comment by xenoterracide** [comment]
https://bitbucket.org/xenoterracide/gradle-plugin-bundle/src/e8dbd583a498cd6053f051f6d2c42bd66a617aef/build.gradle.kts?at=master&fileviewer=file-view-default#build.gradle.kts-56 I wouldn't say it's the solution... but... it works... the solution is for someone to fix their %$@$@!
